-- Supabase Seed File (Generated from modular JSON files)
-- DO NOT EDIT THIS FILE DIRECTLY - Edit the JSON files in data/seeds/ instead
-- Generated on: 2025-11-21T21:07:32.881Z
-- Run with: supabase db reset (drops and recreates with migrations + seeds)

-- Clear existing data (in correct order due to foreign key constraints)
TRUNCATE public.taggables, public.tags CASCADE;
TRUNCATE public.topic_competencies CASCADE;
TRUNCATE public.competency_synonyms CASCADE;
TRUNCATE public.competency_alternatives CASCADE;
TRUNCATE public.competency_prerequisites CASCADE;
TRUNCATE public.topics CASCADE;
TRUNCATE public.competencies CASCADE;
TRUNCATE public.categories CASCADE;
TRUNCATE public.unsplash_images CASCADE;

-- ============================================================
-- UNSPLASH IMAGES
-- ============================================================

-- man writing on paper
-- Usage: Used on /tos page for legal documentation illustration
INSERT INTO public.unsplash_images (photo_id, url, photographer, photographer_username, photographer_url, download_location, alt_description, usage_note)
VALUES ('OQMZwNd3ThU', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?crop=entropy&cs=tinysrgb&fit=crop&h=672&w=1120&fm=jpg&ixid=M3w4MzI5NTB8MHwxfGFsbHx8fHx8fHx8fDE3NjM2NDUyNjV8&ixlib=rb-4.1.0&q=80', 'Scott Graham', 'amstram', 'https://unsplash.com/@amstram?utm_source=ViaProto&utm_medium=referral', 'https://api.unsplash.com/photos/OQMZwNd3ThU/download?ixid=M3w4MzI5NTB8MHwxfGFsbHx8fHx8fHx8fDE3NjM2NDUyNjV8', 'man writing on paper', 'Used on /tos page for legal documentation illustration');

-- we've updated outr privacy policy sign
-- Usage: Used on /privacy-policy page for privacy documentation illustration
INSERT INTO public.unsplash_images (photo_id, url, photographer, photographer_username, photographer_url, download_location, alt_description, usage_note)
VALUES ('HkUDmu2uC9w', 'https://images.unsplash.com/photo-1571751902560-033d0c0f7e5f?crop=bottom&cs=tinysrgb&fit=crop&h=672&w=1120&fm=jpg&ixid=M3w4MzI5NTB8MHwxfGFsbHx8fHx8fHx8fDE3NjM2NTAwNzl8&ixlib=rb-4.1.0&q=80', 'lilartsy', 'lilartsy', 'https://unsplash.com/@lilartsy?utm_source=ViaProto&utm_medium=referral', 'https://api.unsplash.com/photos/HkUDmu2uC9w/download?ixid=M3w4MzI5NTB8MHwxfGFsbHx8fHx8fHx8fDE3NjM2NTAwNzl8', 'we''ve updated outr privacy policy sign', 'Used on /privacy-policy page for privacy documentation illustration');


-- ============================================================
-- CATEGORIES (Hierarchical)
-- ============================================================

-- Information & Technology
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Information & Technology', 'information-technology', 'Technology, software, and digital skills', NULL, 'lucide:computer', 1, true);

  -- Programming
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Programming', 'programming', 'Software development and programming languages', (SELECT id FROM public.categories WHERE slug = 'information-technology'), 'lucide:code-2', 1, true);

    -- Web Development
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Web Development', 'web-development', 'Building websites and web applications', (SELECT id FROM public.categories WHERE slug = 'programming'), 'lucide:globe', 1, true);

      -- Frontend Development
      INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
      VALUES ('Frontend Development', 'frontend-development', 'Client-side web development', (SELECT id FROM public.categories WHERE slug = 'web-development'), 'lucide:smartphone', 1, true);

      -- Full-stack Development
      INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
      VALUES ('Full-stack Development', 'fullstack-development', 'End-to-end web application development', (SELECT id FROM public.categories WHERE slug = 'web-development'), 'lucide:database', 2, true);

      -- Backend Development
      INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
      VALUES ('Backend Development', 'backend-development', 'Server-side web development', (SELECT id FROM public.categories WHERE slug = 'web-development'), 'lucide:server', 3, true);

    -- Mobile Development
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Mobile Development', 'mobile-development', 'Building mobile applications', (SELECT id FROM public.categories WHERE slug = 'programming'), 'lucide:smartphone', 2, true);

    -- Game Development
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Game Development', 'game-development', 'Creating video games and interactive experiences', (SELECT id FROM public.categories WHERE slug = 'programming'), 'lucide:puzzle', 3, true);

    -- Systems Programming
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Systems Programming', 'systems-programming', 'Low-level programming and operating systems', (SELECT id FROM public.categories WHERE slug = 'programming'), 'lucide:cpu', 4, true);

    -- Software Testing
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Software Testing', 'software-testing', 'Testing methodologies and quality assurance', (SELECT id FROM public.categories WHERE slug = 'programming'), 'lucide:check-circle-2', 5, true);

  -- Data & Analytics
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Data & Analytics', 'data-analytics', 'Data science, analysis, and visualization', (SELECT id FROM public.categories WHERE slug = 'information-technology'), 'lucide:bar-chart-3', 2, true);

    -- Data Science
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Data Science', 'data-science', 'Statistical analysis and machine learning', (SELECT id FROM public.categories WHERE slug = 'data-analytics'), 'lucide:flask-conical', 1, true);

    -- Data Engineering
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Data Engineering', 'data-engineering', 'Building data pipelines and infrastructure', (SELECT id FROM public.categories WHERE slug = 'data-analytics'), 'lucide:database', 2, true);

    -- Databases
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Databases', 'databases', 'Database design, management, and optimization', (SELECT id FROM public.categories WHERE slug = 'data-analytics'), 'lucide:database', 3, true);

  -- Cloud & DevOps
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Cloud & DevOps', 'cloud-devops', 'Cloud computing and DevOps practices', (SELECT id FROM public.categories WHERE slug = 'information-technology'), 'lucide:cloud', 3, true);

  -- Information Security
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Information Security', 'information-security', 'Cybersecurity and information protection', (SELECT id FROM public.categories WHERE slug = 'information-technology'), 'lucide:shield-check', 4, true);

    -- Cybersecurity
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Cybersecurity', 'cybersecurity', 'Protecting systems and networks from attacks', (SELECT id FROM public.categories WHERE slug = 'information-security'), 'lucide:lock', 1, true);

-- Design & Creativity
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Design & Creativity', 'design-creativity', 'Visual design, UX, and creative arts', NULL, 'lucide:paintbrush', 2, true);

  -- UI/UX Design
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('UI/UX Design', 'uiux-design', 'User interface and user experience design', (SELECT id FROM public.categories WHERE slug = 'design-creativity'), 'lucide:smartphone', 1, true);

  -- Graphic Design
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Graphic Design', 'graphic-design', 'Visual communication and graphic design', (SELECT id FROM public.categories WHERE slug = 'design-creativity'), 'lucide:image', 2, true);

  -- Motion & 3D
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Motion & 3D', 'motion-3d', 'Motion graphics, animation, and 3D modeling', (SELECT id FROM public.categories WHERE slug = 'design-creativity'), 'lucide:film', 3, true);

  -- Creative Arts
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Creative Arts', 'creative-arts', 'Music, writing, photography, and visual arts', (SELECT id FROM public.categories WHERE slug = 'design-creativity'), 'lucide:music', 4, true);

    -- Photography & Video
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Photography & Video', 'photography-video', 'Photography and videography', (SELECT id FROM public.categories WHERE slug = 'creative-arts'), 'lucide:camera', 1, true);

    -- Music
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Music', 'music', 'Music theory, performance, and production', (SELECT id FROM public.categories WHERE slug = 'creative-arts'), 'lucide:music', 2, true);

    -- Writing
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Writing', 'writing', 'Creative and technical writing', (SELECT id FROM public.categories WHERE slug = 'creative-arts'), 'lucide:pencil', 3, true);

    -- Theater
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Theater', 'theater', 'Acting, directing, and stage production', (SELECT id FROM public.categories WHERE slug = 'creative-arts'), 'lucide:film', 4, true);

    -- Visual Arts
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Visual Arts', 'visual-arts', 'Drawing, painting, and traditional arts', (SELECT id FROM public.categories WHERE slug = 'creative-arts'), 'lucide:paintbrush', 5, true);

  -- Architecture
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Architecture', 'architecture', 'Architectural design and planning', (SELECT id FROM public.categories WHERE slug = 'design-creativity'), 'BuildingOfficeIcon', 5, true);

-- Business & Management
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Business & Management', 'business-management', 'Business skills, management, and entrepreneurship', NULL, 'lucide:briefcase', 3, true);

  -- Product & Project Management
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Product & Project Management', 'product-project-management', 'Product development and project coordination', (SELECT id FROM public.categories WHERE slug = 'business-management'), 'ClipboardDocumentListIcon', 1, true);

  -- Marketing & Sales
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Marketing & Sales', 'marketing-sales', 'Marketing strategy and sales techniques', (SELECT id FROM public.categories WHERE slug = 'business-management'), 'MegaphoneIcon', 2, true);

  -- Leadership & Communication
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Leadership & Communication', 'leadership-communication', 'Leadership skills and professional communication', (SELECT id FROM public.categories WHERE slug = 'business-management'), 'lucide:users', 3, true);

  -- Finance & Accounting
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Finance & Accounting', 'finance-accounting', 'Financial management and accounting principles', (SELECT id FROM public.categories WHERE slug = 'business-management'), 'CurrencyDollarIcon', 4, true);

    -- Personal Finance
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Personal Finance', 'personal-finance', 'Managing personal money and investments', (SELECT id FROM public.categories WHERE slug = 'finance-accounting'), 'BanknotesIcon', 1, true);

    -- Investing & Trading
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Investing & Trading', 'investing-trading', 'Investment strategies and trading', (SELECT id FROM public.categories WHERE slug = 'finance-accounting'), 'lucide:bar-chart-3', 2, true);

    -- Corporate Finance
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Corporate Finance', 'corporate-finance', 'Business financial management', (SELECT id FROM public.categories WHERE slug = 'finance-accounting'), 'BuildingOfficeIcon', 3, true);

  -- Operations & Strategy
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Operations & Strategy', 'operations-strategy', 'Business operations and strategic planning', (SELECT id FROM public.categories WHERE slug = 'business-management'), 'CogIcon', 5, true);

-- Linguistics
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Linguistics', 'linguistics', 'Language learning and speech development', NULL, 'lucide:languages', 4, true);

  -- Languages
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Languages', 'languages', 'Natural language learning', (SELECT id FROM public.categories WHERE slug = 'linguistics'), 'lucide:globe', 1, true);

  -- Speech Development & Pathology
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Speech Development & Pathology', 'speech-development-pathology', 'Speech therapy and language development', (SELECT id FROM public.categories WHERE slug = 'linguistics'), 'MicrophoneIcon', 2, true);

-- Mathematics
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Mathematics', 'mathematics', 'Mathematical theory and applications', NULL, 'lucide:calculator', 5, true);

  -- Foundational Math
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Foundational Math', 'foundational-math', 'Basic mathematical concepts and operations', (SELECT id FROM public.categories WHERE slug = 'mathematics'), 'lucide:graduation-cap', 1, true);

    -- Arithmetic
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Arithmetic', 'arithmetic', 'Basic number operations', (SELECT id FROM public.categories WHERE slug = 'foundational-math'), 'lucide:calculator', 1, true);

    -- Algebra
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Algebra', 'algebra', 'Algebraic expressions and equations', (SELECT id FROM public.categories WHERE slug = 'foundational-math'), 'VariableIcon', 2, true);

    -- Geometry
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Geometry', 'geometry', 'Shapes, spaces, and spatial reasoning', (SELECT id FROM public.categories WHERE slug = 'foundational-math'), 'Square3Stack3DIcon', 3, true);

    -- Trigonometry
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Trigonometry', 'trigonometry', 'Angles and triangular relationships', (SELECT id FROM public.categories WHERE slug = 'foundational-math'), 'ChartPieIcon', 4, true);

  -- Advanced Math
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Advanced Math', 'advanced-math', 'Higher-level mathematical concepts', (SELECT id FROM public.categories WHERE slug = 'mathematics'), 'lucide:graduation-cap', 2, true);

    -- Calculus
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Calculus', 'calculus', 'Differential and integral calculus', (SELECT id FROM public.categories WHERE slug = 'advanced-math'), 'lucide:bar-chart-3', 1, true);

    -- Linear Algebra
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Linear Algebra', 'linear-algebra', 'Vectors, matrices, and linear transformations', (SELECT id FROM public.categories WHERE slug = 'advanced-math'), 'TableCellsIcon', 2, true);

    -- Differential Equations
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Differential Equations', 'differential-equations', 'Equations involving derivatives', (SELECT id FROM public.categories WHERE slug = 'advanced-math'), 'ArrowTrendingUpIcon', 3, true);

  -- Applied Math
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Applied Math', 'applied-math', 'Practical mathematical applications', (SELECT id FROM public.categories WHERE slug = 'mathematics'), 'lucide:bar-chart-3', 3, true);

    -- Statistics & Probability
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Statistics & Probability', 'statistics-probability', 'Data analysis and probability theory', (SELECT id FROM public.categories WHERE slug = 'applied-math'), 'lucide:bar-chart-3', 1, true);

    -- Discrete Mathematics
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Discrete Mathematics', 'discrete-mathematics', 'Mathematical structures for computer science', (SELECT id FROM public.categories WHERE slug = 'applied-math'), 'Squares2X2Icon', 2, true);

    -- Number Theory
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Number Theory', 'number-theory', 'Properties and relationships of numbers', (SELECT id FROM public.categories WHERE slug = 'applied-math'), 'HashtagIcon', 3, true);

-- Science
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Science', 'science', 'Natural sciences and scientific research', NULL, 'lucide:flask-conical', 6, true);

  -- Physical Sciences
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Physical Sciences', 'physical-sciences', 'Physics, chemistry, and physical phenomena', (SELECT id FROM public.categories WHERE slug = 'science'), 'BoltIcon', 1, true);

    -- Physics
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Physics', 'physics', 'Matter, energy, and fundamental forces', (SELECT id FROM public.categories WHERE slug = 'physical-sciences'), 'BoltIcon', 1, true);

    -- Chemistry
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Chemistry', 'chemistry', 'Chemical elements and reactions', (SELECT id FROM public.categories WHERE slug = 'physical-sciences'), 'lucide:flask-conical', 2, true);

    -- Astronomy
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Astronomy', 'astronomy', 'Celestial objects and universe', (SELECT id FROM public.categories WHERE slug = 'physical-sciences'), 'lucide:sparkles', 3, true);

  -- Life Sciences
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Life Sciences', 'life-sciences', 'Biology and living organisms', (SELECT id FROM public.categories WHERE slug = 'science'), 'lucide:heart', 2, true);

    -- Biology
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Biology', 'biology', 'Living organisms and life processes', (SELECT id FROM public.categories WHERE slug = 'life-sciences'), 'lucide:sparkles', 1, true);

    -- Genetics
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Genetics', 'genetics', 'Heredity and genetic variation', (SELECT id FROM public.categories WHERE slug = 'life-sciences'), 'DocumentMagnifyingGlassIcon', 2, true);

    -- Neuroscience
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Neuroscience', 'neuroscience', 'Brain and nervous system', (SELECT id FROM public.categories WHERE slug = 'life-sciences'), 'lucide:cpu', 3, true);

  -- Environmental Science
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Environmental Science', 'environmental-science', 'Environment and ecosystems', (SELECT id FROM public.categories WHERE slug = 'science'), 'lucide:globe', 3, true);

-- Personal Development
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Personal Development', 'personal-development', 'Self-improvement and life skills', NULL, 'UserIcon', 7, true);

  -- Productivity & Time Management
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Productivity & Time Management', 'productivity-time-management', 'Efficiency and time optimization', (SELECT id FROM public.categories WHERE slug = 'personal-development'), 'ClockIcon', 1, true);

  -- Cognitive Skills
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Cognitive Skills', 'cognitive-skills', 'Thinking and learning abilities', (SELECT id FROM public.categories WHERE slug = 'personal-development'), 'LightBulbIcon', 2, true);

    -- Critical Thinking
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Critical Thinking', 'critical-thinking', 'Logical analysis and reasoning', (SELECT id FROM public.categories WHERE slug = 'cognitive-skills'), 'lucide:graduation-cap', 1, true);

    -- Memory & Learning
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Memory & Learning', 'memory-learning', 'Retention and learning techniques', (SELECT id FROM public.categories WHERE slug = 'cognitive-skills'), 'BookOpenIcon', 2, true);

    -- Problem Solving
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Problem Solving', 'problem-solving', 'Analytical problem resolution', (SELECT id FROM public.categories WHERE slug = 'cognitive-skills'), 'lucide:puzzle', 3, true);

  -- Communication & Interpersonal
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Communication & Interpersonal', 'communication-interpersonal', 'Relationship and communication skills', (SELECT id FROM public.categories WHERE slug = 'personal-development'), 'lucide:messages-square', 3, true);

  -- Mindfulness & Wellness
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Mindfulness & Wellness', 'mindfulness-wellness', 'Mental well-being and awareness', (SELECT id FROM public.categories WHERE slug = 'personal-development'), 'lucide:heart', 4, true);

-- Health & Fitness
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Health & Fitness', 'health-fitness', 'Physical health and wellness', NULL, 'lucide:heart', 8, true);

  -- Fitness & Exercise
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Fitness & Exercise', 'fitness-exercise', 'Physical training and exercise', (SELECT id FROM public.categories WHERE slug = 'health-fitness'), 'BoltIcon', 1, true);

    -- Strength Training
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Strength Training', 'strength-training', 'Resistance and weight training', (SELECT id FROM public.categories WHERE slug = 'fitness-exercise'), 'FireIcon', 1, true);

    -- Cardio & Endurance
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Cardio & Endurance', 'cardio-endurance', 'Cardiovascular fitness', (SELECT id FROM public.categories WHERE slug = 'fitness-exercise'), 'lucide:heart', 2, true);

    -- Flexibility & Mobility
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Flexibility & Mobility', 'flexibility-mobility', 'Stretching and movement quality', (SELECT id FROM public.categories WHERE slug = 'fitness-exercise'), 'ArrowsRightLeftIcon', 3, true);

  -- Nutrition & Diet
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Nutrition & Diet', 'nutrition-diet', 'Healthy eating and nutrition', (SELECT id FROM public.categories WHERE slug = 'health-fitness'), 'CakeIcon', 2, true);

  -- Mental Health
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Mental Health', 'mental-health', 'Psychological well-being', (SELECT id FROM public.categories WHERE slug = 'health-fitness'), 'lucide:heart', 3, true);

  -- Holistic Health
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Holistic Health', 'holistic-health', 'Alternative and integrative health', (SELECT id FROM public.categories WHERE slug = 'health-fitness'), 'lucide:sparkles', 4, true);

    -- Yoga
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Yoga', 'yoga', 'Mind-body practice and movement', (SELECT id FROM public.categories WHERE slug = 'holistic-health'), 'UserIcon', 1, true);

    -- Meditation
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Meditation', 'meditation', 'Mindfulness and meditation practices', (SELECT id FROM public.categories WHERE slug = 'holistic-health'), 'lucide:sparkles', 2, true);

    -- Alternative Medicine
    INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
    VALUES ('Alternative Medicine', 'alternative-medicine', 'Complementary health practices', (SELECT id FROM public.categories WHERE slug = 'holistic-health'), 'lucide:flask-conical', 3, true);

-- Home & Lifestyle
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Home & Lifestyle', 'home-lifestyle', 'Practical skills for home, garden, and daily living', NULL, 'lucide:home', 9, true);

-- Recreation & Hobbies
INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
VALUES ('Recreation & Hobbies', 'recreation-hobbies', 'Games, sports, and recreational activities', NULL, 'lucide:gamepad-2', 10, true);

  -- Fiber Arts & Crafts
  INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)
  VALUES ('Fiber Arts & Crafts', 'fiber-arts-crafts', 'Textile arts, sewing, knitting, and fiber crafts', (SELECT id FROM public.categories WHERE slug = 'design-creativity'), 'lucide:scissors', 5, true);


-- ============================================================
-- COMPETENCIES
-- ============================================================

-- Algorithms
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Algorithms',
  'algorithms',
  'Step-by-step procedures for solving computational problems efficiently',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:network'
);

-- Angular
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Angular',
  'angular',
  'TypeScript-based framework for building scalable web applications',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:angular-icon'
);

-- Bash
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Bash',
  'bash',
  'Unix shell and command language for automation and system administration',
  (SELECT id FROM public.categories WHERE slug = 'systems-programming'),
  'devicon:bash'
);

-- C
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'C',
  'c',
  'Low-level systems programming language known for performance and hardware control',
  (SELECT id FROM public.categories WHERE slug = 'systems-programming'),
  'devicon:c'
);

-- C++
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'C++',
  'cpp',
  'High-performance programming language for systems, games, and applications requiring speed',
  (SELECT id FROM public.categories WHERE slug = 'systems-programming'),
  'logos:c-plusplus'
);

-- C#
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'C#',
  'csharp',
  'Modern object-oriented language for .NET development, games (Unity), and enterprise applications',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'devicon:csharp'
);

-- CSS
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'CSS',
  'css',
  'Style sheet language for web pages',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:css-3-official'
);

-- Data Structures
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Data Structures',
  'data-structures',
  'Ways of organizing and storing data for efficient access and modification',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:database'
);

-- Debugging
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Debugging',
  'debugging',
  'Identifying and fixing errors in software',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:bug'
);

-- Design Patterns
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Design Patterns',
  'design-patterns',
  'Reusable solutions to common software design problems',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:component'
);

-- Django
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Django',
  'django',
  'High-level Python web framework',
  (SELECT id FROM public.categories WHERE slug = 'backend-development'),
  'logos:django-icon'
);

-- Flask
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Flask',
  'flask',
  'Lightweight Python web framework',
  (SELECT id FROM public.categories WHERE slug = 'backend-development'),
  'logos:flask'
);

-- Functional Programming
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Functional Programming',
  'functional-programming',
  'Programming paradigm treating computation as evaluation of mathematical functions',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:function-square'
);

-- Go
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Go',
  'go',
  'Simple and efficient language for building scalable backend services and cloud infrastructure',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'logos:go'
);

-- HTML
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'HTML',
  'html',
  'Markup language for web pages',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:html-5'
);

-- Jasmine
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Jasmine',
  'jasmine',
  'Lightweight JavaScript testing framework without magic',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:jasmine'
);

-- Java
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Java',
  'java',
  'Object-oriented programming language used for enterprise applications, Android development, and backend systems',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'logos:java'
);

-- JavaScript
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'JavaScript',
  'javascript',
  'Programming language of the web',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'logos:javascript'
);

-- Jest
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Jest',
  'jest',
  'JavaScript testing framework with an emphasis on simplicity',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:jest'
);

-- Kotlin
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Kotlin',
  'kotlin',
  'Modern JVM language for Android development and server-side applications',
  (SELECT id FROM public.categories WHERE slug = 'mobile-development'),
  'logos:kotlin-icon'
);

-- Lua
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Lua',
  'lua',
  'Lightweight scripting language used in game development and embedded systems',
  (SELECT id FROM public.categories WHERE slug = 'game-development'),
  'logos:lua'
);

-- Mocha
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Mocha',
  'mocha',
  'Flexible JavaScript testing framework that aims to be fun to use',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:mocha'
);

-- Node.js
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Node.js',
  'nodejs',
  'Cross-platform JavaScript runtime that lets you make almost anything',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:nodejs-icon'
);

-- Nuxt
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Nuxt',
  'nuxt',
  'Full stack web application framework for Vue.js',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:nuxt-icon'
);

-- Objective-C
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Objective-C',
  'objective-c',
  'Object-oriented language used for Apple platform development before Swift',
  (SELECT id FROM public.categories WHERE slug = 'mobile-development'),
  'devicon:objectivec'
);

-- Object-Oriented Programming
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Object-Oriented Programming',
  'oop',
  'Programming paradigm based on objects containing data and code',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:boxes'
);

-- Perl
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Perl',
  'perl',
  'Text processing and system administration language',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'devicon:perl'
);

-- PHP
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'PHP',
  'php',
  'Server-side scripting language widely used for web development',
  (SELECT id FROM public.categories WHERE slug = 'backend-development'),
  'logos:php'
);

-- Pinia
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Pinia',
  'pinia',
  'A more modular and intuitive store for Vue.js',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:pinia'
);

-- PowerShell
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'PowerShell',
  'powershell',
  'Task automation and configuration management framework from Microsoft',
  (SELECT id FROM public.categories WHERE slug = 'systems-programming'),
  'devicon:powershell'
);

-- Progressive Web App
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Progressive Web App',
  'pwa',
  'Web applications with native app-like features like push notifications and offline-capability',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:pwa'
);

-- Python
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Python',
  'python',
  'High-level programming language',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'logos:python'
);

-- R
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'R',
  'r',
  'Statistical programming language for data analysis and visualization',
  (SELECT id FROM public.categories WHERE slug = 'data-science'),
  'devicon:r'
);

-- React
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'React',
  'react',
  'JavaScript library for building user interfaces',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:react'
);

-- Regular Expressions
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Regular Expressions',
  'regular-expressions',
  'Pattern matching for text processing and string manipulation',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:search'
);

-- Ruby
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Ruby',
  'ruby',
  'Dynamic programming language known for elegant syntax and Rails web framework',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'logos:ruby'
);

-- Rust
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Rust',
  'rust',
  'Memory-safe systems programming language for performance-critical applications',
  (SELECT id FROM public.categories WHERE slug = 'systems-programming'),
  'logos:rust'
);

-- Testing
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Testing',
  'software-testing',
  'Practices and techniques for verifying software quality and correctness',
  (SELECT id FROM public.categories WHERE slug = 'software-testing'),
  'lucide:check-circle-2'
);

-- Spanish
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Spanish',
  'spanish',
  'Romance language spoken by over 500 million people worldwide',
  (SELECT id FROM public.categories WHERE slug = 'natural-languages'),
  'lucide:message-circle'
);

-- SQL
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'SQL',
  'sql',
  'Language for managing and querying relational databases',
  (SELECT id FROM public.categories WHERE slug = 'databases'),
  'lucide:database'
);

-- Swift
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Swift',
  'swift',
  'Modern programming language for iOS, macOS, and Apple platform development',
  (SELECT id FROM public.categories WHERE slug = 'mobile-development'),
  'logos:swift'
);

-- TypeScript
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'TypeScript',
  'typescript',
  'Typed superset of JavaScript for safer code',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'logos:typescript-icon'
);

-- Version Control
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Version Control',
  'version-control',
  'Systems for tracking changes in code and collaborating with others',
  (SELECT id FROM public.categories WHERE slug = 'programming'),
  'lucide:git-branch'
);

-- Vue.js
INSERT INTO public.competencies (name, slug, description, category_id, icon)
VALUES (
  'Vue.js',
  'vuejs',
  'Progressive JavaScript framework for building user interfaces',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development'),
  'logos:vue'
);


-- ============================================================
-- COMPETENCY SYNONYMS
-- ============================================================

-- Algorithms synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'algorithms'), 'Algorithm Design');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'algorithms'), 'Algorithmic Thinking');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'algorithms'), 'Problem Solving Algorithms');

-- Angular synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'angular'), 'AngularJS');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'angular'), 'Angular 2+');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'angular'), 'Angular Framework');

-- Bash synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'bash'), 'Bash Scripting');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'bash'), 'Shell Scripting');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'bash'), 'Bourne Again Shell');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'bash'), 'Linux Shell');

-- C synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'c'), 'C Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'c'), 'ANSI C');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'c'), 'C Programming');

-- C++ synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'cpp'), 'C Plus Plus');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'cpp'), 'CPP');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'cpp'), 'C++ Programming');

-- C# synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'csharp'), 'C Sharp');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'csharp'), 'CSharp');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'csharp'), 'C# Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'csharp'), '.NET Language');

-- CSS synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'css'), 'CSS3');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'css'), 'Cascading Style Sheets');

-- Data Structures synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'data-structures'), 'Data Structure Design');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'data-structures'), 'DS');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'data-structures'), 'Data Organization');

-- Debugging synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'debugging'), 'Bug Fixing');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'debugging'), 'Troubleshooting');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'debugging'), 'Code Debugging');

-- Design Patterns synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'design-patterns'), 'Software Design Patterns');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'design-patterns'), 'Gang of Four Patterns');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'design-patterns'), 'GoF Patterns');

-- Django synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'django'), 'Django Framework');

-- Flask synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'flask'), 'Flask Framework');

-- Functional Programming synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'functional-programming'), 'FP');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'functional-programming'), 'Functional Programming Paradigm');

-- Go synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'go'), 'Golang');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'go'), 'Go Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'go'), 'Go Programming');

-- HTML synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'html'), 'HTML5');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'html'), 'HyperText Markup Language');

-- Java synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'java'), 'Java Programming');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'java'), 'Java Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'java'), 'OpenJDK');

-- JavaScript synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'javascript'), 'JS');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'javascript'), 'ECMAScript');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'javascript'), 'ES6');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'javascript'), 'ES2015+');

-- Kotlin synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'kotlin'), 'Kotlin Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'kotlin'), 'Kotlin Programming');

-- Lua synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'lua'), 'Lua Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'lua'), 'Lua Scripting');

-- Node.js synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'nodejs'), 'node');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'nodejs'), 'nodejs');

-- Objective-C synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'objective-c'), 'ObjC');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'objective-c'), 'Objective C');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'objective-c'), 'Obj-C');

-- Object-Oriented Programming synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'oop'), 'OOP');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'oop'), 'Object Oriented Programming');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'oop'), 'OO Programming');

-- Perl synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'perl'), 'Perl Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'perl'), 'Perl Programming');

-- PHP synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'php'), 'PHP Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'php'), 'PHP Programming');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'php'), 'Hypertext Preprocessor');

-- PowerShell synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'powershell'), 'PowerShell Scripting');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'powershell'), 'Windows PowerShell');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'powershell'), 'pwsh');

-- Progressive Web App synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'pwa'), 'pwa');

-- Python synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'python'), 'Python Programming');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'python'), 'Python3');

-- R synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'r'), 'R Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'r'), 'R Programming');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'r'), 'R Statistical Computing');

-- React synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'react'), 'React.js');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'react'), 'ReactJS');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'react'), 'React Framework');

-- Regular Expressions synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'regular-expressions'), 'RegEx');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'regular-expressions'), 'RegExp');

-- Ruby synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'ruby'), 'Ruby Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'ruby'), 'Ruby Programming');

-- Rust synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'rust'), 'Rust Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'rust'), 'Rust Programming');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'rust'), 'Rustlang');

-- Testing synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'software-testing'), 'Unit Testing');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'software-testing'), 'Test-Driven Development');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'software-testing'), 'TDD');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'software-testing'), 'QA');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'software-testing'), 'Quality Assurance');

-- Spanish synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'spanish'), 'Español');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'spanish'), 'Spanish Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'spanish'), 'Castellano');

-- SQL synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'sql'), 'Structured Query Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'sql'), 'Database Queries');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'sql'), 'SQL Programming');

-- Swift synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'swift'), 'Swift Language');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'swift'), 'Swift Programming');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'swift'), 'Apple Swift');

-- TypeScript synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'typescript'), 'TS');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'typescript'), 'TypeScript Language');

-- Version Control synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'version-control'), 'Source Control');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'version-control'), 'VCS');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'version-control'), 'Git');

-- Vue.js synonyms
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'vuejs'), 'Vue');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'vuejs'), 'VueJS');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'vuejs'), 'Vue Framework');
INSERT INTO public.competency_synonyms (competency_id, synonym)
VALUES ((SELECT id FROM public.competencies WHERE slug = 'vuejs'), 'Vue 3');


-- ============================================================
-- COMPETENCY PREREQUISITES
-- ============================================================

-- Algorithms prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'algorithms'),
  (SELECT id FROM public.competencies WHERE slug = 'data-structures'),
  'recommended',
  'Understanding data structures helps with algorithm implementation and optimization'
);

-- Angular prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  'required',
  'Angular is written in TypeScript, so familiarity is required to pick it up quickly'
);

-- C++ prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'cpp'),
  (SELECT id FROM public.competencies WHERE slug = 'c'),
  'recommended',
  'Understanding C helps with C++ fundamentals, but not strictly required'
);

-- Design Patterns prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'design-patterns'),
  (SELECT id FROM public.competencies WHERE slug = 'oop'),
  'required',
  'Most design patterns are based on object-oriented principles'
);

-- Django prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'django'),
  (SELECT id FROM public.competencies WHERE slug = 'python'),
  'required',
  'Python basics required for Django development'
);

-- Flask prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'flask'),
  (SELECT id FROM public.competencies WHERE slug = 'python'),
  'required',
  'Python basics required for Flask development'
);

-- Kotlin prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'kotlin'),
  (SELECT id FROM public.competencies WHERE slug = 'java'),
  'recommended',
  'Understanding Java helps with Kotlin, but not required as Kotlin can be learned independently'
);

-- Objective-C prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'objective-c'),
  (SELECT id FROM public.competencies WHERE slug = 'c'),
  'required',
  'Objective-C is built on top of C'
);

-- React prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'react'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  'required',
  'JavaScript fundamentals required before learning React'
);

-- TypeScript prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  'required',
  'TypeScript is a superset of JavaScript, so JavaScript fundamentals are essential'
);

-- Vue.js prerequisites
INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  'required',
  'JavaScript fundamentals required before learning Vue.js'
);


-- ============================================================
-- COMPETENCY ALTERNATIVES
-- ============================================================

-- C++ alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'cpp'),
  (SELECT id FROM public.competencies WHERE slug = 'rust'),
  'similar',
  'Rust offers similar performance to C++ with memory safety guarantees'
);

-- C# alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'csharp'),
  (SELECT id FROM public.competencies WHERE slug = 'java'),
  'similar',
  'Java and C# share similar syntax and object-oriented paradigms'
);

-- Flask alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'flask'),
  (SELECT id FROM public.competencies WHERE slug = 'django'),
  'similar',
  'Both are Python web frameworks. Flask is lightweight, Django is full-featured.'
);

-- Go alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'go'),
  (SELECT id FROM public.competencies WHERE slug = 'rust'),
  'similar',
  'Both are modern systems languages with strong concurrency support'
);

-- Java alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'java'),
  (SELECT id FROM public.competencies WHERE slug = 'csharp'),
  'similar',
  'C# and Java share similar syntax and object-oriented paradigms, both used for enterprise development'
);
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'java'),
  (SELECT id FROM public.competencies WHERE slug = 'kotlin'),
  'similar',
  'Kotlin is a modern alternative to Java, especially for Android development, and runs on the JVM'
);

-- Kotlin alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'kotlin'),
  (SELECT id FROM public.competencies WHERE slug = 'java'),
  'similar',
  'Kotlin is designed as a better Java, runs on JVM, and is interoperable with Java'
);

-- PHP alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'php'),
  (SELECT id FROM public.competencies WHERE slug = 'python'),
  'similar',
  'Both are popular for backend web development'
);
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'php'),
  (SELECT id FROM public.competencies WHERE slug = 'nodejs'),
  'similar',
  'Both are commonly used for server-side web development'
);

-- PowerShell alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'powershell'),
  (SELECT id FROM public.competencies WHERE slug = 'bash'),
  'similar',
  'Both are shell scripting languages, PowerShell for Windows/cross-platform, Bash for Unix/Linux'
);

-- R alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'r'),
  (SELECT id FROM public.competencies WHERE slug = 'python'),
  'similar',
  'Python with libraries like Pandas is often used as an alternative to R for data science'
);

-- React alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'react'),
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  'similar',
  'Both are popular JavaScript frontend frameworks. React has larger ecosystem, Vue.js has gentler learning curve.'
);
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'react'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  'similar',
  'Both are popular frontend frameworks. React is more flexible, Angular is more opinionated and feature-complete.'
);

-- Ruby alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'ruby'),
  (SELECT id FROM public.competencies WHERE slug = 'python'),
  'similar',
  'Both are dynamic, high-level languages with clean syntax and strong web frameworks'
);

-- Rust alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'rust'),
  (SELECT id FROM public.competencies WHERE slug = 'cpp'),
  'similar',
  'Both are systems languages, but Rust provides memory safety without garbage collection'
);
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'rust'),
  (SELECT id FROM public.competencies WHERE slug = 'go'),
  'similar',
  'Both are modern systems languages with strong concurrency, but different philosophies'
);

-- Swift alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'swift'),
  (SELECT id FROM public.competencies WHERE slug = 'objective-c'),
  'replaces',
  'Swift is the modern replacement for Objective-C in Apple ecosystem'
);

-- Vue.js alternatives
INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)
VALUES (
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  'similar',
  'Both are complete frontend frameworks. Vue.js is more approachable, Angular is better for enterprise apps.'
);


-- ============================================================
-- TOPICS
-- ============================================================

-- Advanced TypeScript patterns and generics
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Advanced TypeScript patterns and generics',
  'advanced-typescript-patterns',
  'Master advanced TypeScript features including generics, utility types, and type inference',
  (SELECT id FROM public.categories WHERE slug = 'programming')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'advanced-typescript-patterns'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'advanced-typescript-patterns'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Building games for web browsers with Vue.js
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Building games for web browsers with Vue.js',
  'building-browser-games-vuejs',
  'Create interactive browser-based games using Vue.js components and reactivity',
  (SELECT id FROM public.categories WHERE slug = 'game-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-browser-games-vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-browser-games-vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Building interactive UIs with React
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Building interactive UIs with React',
  'building-interactive-uis-with-react',
  'Learn to create dynamic, interactive user interfaces using React''s component-based architecture',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-interactive-uis-with-react'),
  (SELECT id FROM public.competencies WHERE slug = 'react'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-interactive-uis-with-react'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-interactive-uis-with-react'),
  (SELECT id FROM public.competencies WHERE slug = 'html'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-interactive-uis-with-react'),
  (SELECT id FROM public.competencies WHERE slug = 'css'),
  false
);

-- Building reactive web applications with Vue.js
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Building reactive web applications with Vue.js',
  'building-reactive-web-apps-vuejs',
  'Create responsive, data-driven web applications using Vue.js''s reactive framework',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-reactive-web-apps-vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-reactive-web-apps-vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-reactive-web-apps-vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'html'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-reactive-web-apps-vuejs'),
  (SELECT id FROM public.competencies WHERE slug = 'css'),
  false
);

-- Building web applications with Python and Django
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Building web applications with Python and Django',
  'building-web-applications-with-python-django',
  'Learn to build full-featured web applications using Python and Django',
  (SELECT id FROM public.categories WHERE slug = 'backend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-web-applications-with-python-django'),
  (SELECT id FROM public.competencies WHERE slug = 'django'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-web-applications-with-python-django'),
  (SELECT id FROM public.competencies WHERE slug = 'python'),
  false
);

-- Building web applications with Python and Flask
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Building web applications with Python and Flask',
  'building-web-applications-with-python-flask',
  'Learn to build small and flexible web applications using Python and Flask',
  (SELECT id FROM public.categories WHERE slug = 'backend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-web-applications-with-python-flask'),
  (SELECT id FROM public.competencies WHERE slug = 'flask'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'building-web-applications-with-python-flask'),
  (SELECT id FROM public.competencies WHERE slug = 'python'),
  false
);

-- Conversational Spanish for travelers
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Conversational Spanish for travelers',
  'conversational-spanish-for-travelers',
  'Learn essential Spanish phrases and conversations for travel',
  (SELECT id FROM public.categories WHERE slug = 'languages')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'conversational-spanish-for-travelers'),
  (SELECT id FROM public.competencies WHERE slug = 'spanish'),
  true
);

-- Enterprise-scale applications with Angular
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Enterprise-scale applications with Angular',
  'enterprise-apps-angular',
  'Build large-scale, maintainable enterprise applications using Angular''s robust architecture',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'enterprise-apps-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'enterprise-apps-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  false
);

-- Full-stack development with TypeScript
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Full-stack development with TypeScript',
  'fullstack-development-typescript',
  'Build end-to-end type-safe applications with TypeScript across frontend and backend',
  (SELECT id FROM public.categories WHERE slug = 'fullstack-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'fullstack-development-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'fullstack-development-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Migrating JavaScript projects to TypeScript
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Migrating JavaScript projects to TypeScript',
  'migrating-javascript-typescript',
  'Incrementally adopt TypeScript in existing JavaScript codebases',
  (SELECT id FROM public.categories WHERE slug = 'programming')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'migrating-javascript-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'migrating-javascript-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Building Node.js APIs with TypeScript
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Building Node.js APIs with TypeScript',
  'nodejs-apis-typescript',
  'Create type-safe backend APIs using TypeScript and Node.js',
  (SELECT id FROM public.categories WHERE slug = 'backend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'nodejs-apis-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'nodejs'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'nodejs-apis-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'nodejs-apis-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Progressive Web Apps with Angular
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Progressive Web Apps with Angular',
  'pwa-angular',
  'Create offline-capable, installable Progressive Web Apps using Angular',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'pwa-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'pwa'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'pwa-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'pwa-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  false
);

-- Reactive forms in Angular applications
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Reactive forms in Angular applications',
  'reactive-forms-angular',
  'Master complex form handling and validation with Angular reactive forms',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'reactive-forms-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'reactive-forms-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  false
);

-- Scaffold performant Vue.js applications with Nuxt
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Scaffold performant Vue.js applications with Nuxt',
  'scaffold-vuejs-apps-nuxt',
  'Build server-rendered and statically generated Vue.js apps with Nuxt framework',
  (SELECT id FROM public.categories WHERE slug = 'fullstack-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'scaffold-vuejs-apps-nuxt'),
  (SELECT id FROM public.competencies WHERE slug = 'nuxt'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'scaffold-vuejs-apps-nuxt'),
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'scaffold-vuejs-apps-nuxt'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Server-side rendering with Angular Universal
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Server-side rendering with Angular Universal',
  'ssr-angular-universal',
  'Implement server-side rendering for improved performance and SEO with Angular Universal',
  (SELECT id FROM public.categories WHERE slug = 'fullstack-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'ssr-angular-universal'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'ssr-angular-universal'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  false
);

-- State management with NgRx in Angular
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'State management with NgRx in Angular',
  'state-management-ngrx-angular',
  'Manage complex application state using NgRx and Redux patterns in Angular',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'state-management-ngrx-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'state-management-ngrx-angular'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  false
);

-- Managing frontend state with Vue.js and Pinia
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Managing frontend state with Vue.js and Pinia',
  'state-management-vuejs-pinia',
  'Master centralized state management in Vue.js applications using Pinia',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'state-management-vuejs-pinia'),
  (SELECT id FROM public.competencies WHERE slug = 'pinia'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'state-management-vuejs-pinia'),
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'state-management-vuejs-pinia'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Testing Angular applications with Jasmine
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Testing Angular applications with Jasmine',
  'testing-angular-jasmine',
  'Write unit and integration tests for Angular apps using Jasmine and Karma',
  (SELECT id FROM public.categories WHERE slug = 'software-testing')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-angular-jasmine'),
  (SELECT id FROM public.competencies WHERE slug = 'jasmine'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-angular-jasmine'),
  (SELECT id FROM public.competencies WHERE slug = 'angular'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-angular-jasmine'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  false
);

-- Testing Vue.js applications with Jest
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Testing Vue.js applications with Jest',
  'testing-vuejs-jest',
  'Write comprehensive unit and component tests for Vue.js apps using Jest',
  (SELECT id FROM public.categories WHERE slug = 'software-testing')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-vuejs-jest'),
  (SELECT id FROM public.competencies WHERE slug = 'jest'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-vuejs-jest'),
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-vuejs-jest'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Testing Vue.js applications with Mocha
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Testing Vue.js applications with Mocha',
  'testing-vuejs-mocha',
  'Write comprehensive unit and component tests for Vue.js apps using Mocha',
  (SELECT id FROM public.categories WHERE slug = 'software-testing')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-vuejs-mocha'),
  (SELECT id FROM public.competencies WHERE slug = 'mocha'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-vuejs-mocha'),
  (SELECT id FROM public.competencies WHERE slug = 'vuejs'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'testing-vuejs-mocha'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Type-safe JavaScript development with TypeScript
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Type-safe JavaScript development with TypeScript',
  'type-safe-javascript-typescript',
  'Write safer, more maintainable JavaScript code using TypeScript''s static typing',
  (SELECT id FROM public.categories WHERE slug = 'programming')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'type-safe-javascript-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'type-safe-javascript-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

-- Type-safe React applications with TypeScript
INSERT INTO public.topics (name, slug, description, category_id)
VALUES (
  'Type-safe React applications with TypeScript',
  'type-safe-react-typescript',
  'Build robust React applications with TypeScript for improved type safety and developer experience',
  (SELECT id FROM public.categories WHERE slug = 'frontend-development')
);

INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'type-safe-react-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'typescript'),
  true
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'type-safe-react-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'react'),
  false
);
INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)
VALUES (
  (SELECT id FROM public.topics WHERE slug = 'type-safe-react-typescript'),
  (SELECT id FROM public.competencies WHERE slug = 'javascript'),
  false
);

