#!/usr/bin/env tsx

/**
 * Generate supabase/seed.sql from modular JSON seed files
 *
 * This script reads from:
 * - data/seeds/categories.json
 * - data/seeds/competencies/*.json
 * - data/seeds/topics/*.json
 * - data/seeds/unsplash_images.json
 *
 * And generates: supabase/seed.sql
 */

import fs from 'fs';
import path from 'path';

interface Category {
  name: string;
  slug: string;
  description: string;
  icon: string;
  display_order: number;
  parent_slug: string | null;
}

interface Competency {
  name: string;
  slug: string;
  description: string;
  category_slug: string;
  synonyms?: string[];
  icon?: string;
  prerequisites?: {
    prerequisite_slug: string;
    prerequisite_level: string;
    notes?: string;
  }[];
  alternatives?: {
    alternative_slug: string;
    relationship_type: string;
    notes?: string;
  }[];
}

interface Topic {
  name: string;
  slug: string;
  description: string;
  category_slug: string;
  competencies: {
    competency_slug: string;
    is_primary: boolean;
  }[];
}

interface UnsplashImage {
  photo_id: string;
  url: string;
  photographer: string;
  photographer_username: string;
  photographer_url: string;
  download_location: string;
  alt_description: string;
  usage_note: string;
}

// SQL escape helper
function sqlEscape(str: string | null | undefined): string {
  if (str === null || str === undefined) return 'NULL';
  return `'${str.replace(/'/g, "''")}'`;
}

function generateHeader(): string {
  return `-- Supabase Seed File (Generated from modular JSON files)
-- DO NOT EDIT THIS FILE DIRECTLY - Edit the JSON files in data/seeds/ instead
-- Generated on: ${new Date().toISOString()}
-- Run with: supabase db reset (drops and recreates with migrations + seeds)

-- Clear existing data (in correct order due to foreign key constraints)
TRUNCATE public.taggables, public.tags CASCADE;
TRUNCATE public.topic_competencies CASCADE;
TRUNCATE public.competency_synonyms CASCADE;
TRUNCATE public.competency_alternatives CASCADE;
TRUNCATE public.competency_prerequisites CASCADE;
TRUNCATE public.topics CASCADE;
TRUNCATE public.competencies CASCADE;
TRUNCATE public.categories CASCADE;
TRUNCATE public.unsplash_images CASCADE;

`;
}

function generateUnsplashImagesSQL(images: UnsplashImage[]): string {
  if (images.length === 0) return '';

  let sql = `-- ============================================================
-- UNSPLASH IMAGES
-- ============================================================

`;

  for (const img of images) {
    sql += `-- ${img.alt_description}\n`;
    sql += `-- Usage: ${img.usage_note}\n`;
    sql += `INSERT INTO public.unsplash_images (photo_id, url, photographer, photographer_username, photographer_url, download_location, alt_description, usage_note)\n`;
    sql += `VALUES (${sqlEscape(img.photo_id)}, ${sqlEscape(img.url)}, ${sqlEscape(img.photographer)}, ${sqlEscape(img.photographer_username)}, ${sqlEscape(img.photographer_url)}, ${sqlEscape(img.download_location)}, ${sqlEscape(img.alt_description)}, ${sqlEscape(img.usage_note)});\n\n`;
  }

  return sql;
}

function sortCategoriesHierarchically(categories: Category[]): Category[] {
  const sorted: Category[] = [];
  const categoryMap = new Map<string, Category>();

  // Build map
  for (const cat of categories) {
    categoryMap.set(cat.slug, cat);
  }

  // Recursive function to add category and its descendants
  function addCategoryAndDescendants(cat: Category) {
    if (sorted.find(c => c.slug === cat.slug)) return; // Already added

    // Add parent first if it exists
    if (cat.parent_slug) {
      const parent = categoryMap.get(cat.parent_slug);
      if (parent) {
        addCategoryAndDescendants(parent);
      }
    }

    sorted.push(cat);
  }

  // Sort by display_order first, then process
  const orderedCategories = [...categories].sort((a, b) => {
    if (a.parent_slug === b.parent_slug) {
      return a.display_order - b.display_order;
    }
    return 0;
  });

  for (const cat of orderedCategories) {
    addCategoryAndDescendants(cat);
  }

  return sorted;
}

function generateCategoriesSQL(categories: Category[]): string {
  const sorted = sortCategoriesHierarchically(categories);

  let sql = `
-- ============================================================
-- CATEGORIES (Hierarchical)
-- ============================================================

`;

  // Track indentation level for readability
  const indentMap = new Map<string, number>();

  for (const cat of categories) {
    if (!cat.parent_slug) {
      indentMap.set(cat.slug, 0);
    } else {
      const parentIndent = indentMap.get(cat.parent_slug) || 0;
      indentMap.set(cat.slug, parentIndent + 1);
    }
  }

  for (const cat of sorted) {
    const indent = '  '.repeat(indentMap.get(cat.slug) || 0);
    const comment = `${indent}-- ${cat.name}\n`;
    const parentIdSQL = cat.parent_slug
      ? `(SELECT id FROM public.categories WHERE slug = ${sqlEscape(cat.parent_slug)})`
      : 'NULL';

    sql += comment;
    sql += `${indent}INSERT INTO public.categories (name, slug, description, parent_id, icon, display_order, is_active)\n`;
    sql += `${indent}VALUES (${sqlEscape(cat.name)}, ${sqlEscape(cat.slug)}, ${sqlEscape(cat.description)}, ${parentIdSQL}, ${sqlEscape(cat.icon)}, ${cat.display_order}, true);\n\n`;
  }

  return sql;
}

function generateCompetenciesSQL(competencies: Competency[]): string {
  let sql = `
-- ============================================================
-- COMPETENCIES
-- ============================================================

`;

  // Sort by slug for consistency
  const sorted = [...competencies].sort((a, b) => a.slug.localeCompare(b.slug));

  // PHASE 1: Insert all competencies first
  for (const comp of sorted) {
    sql += `-- ${comp.name}\n`;
    sql += `INSERT INTO public.competencies (name, slug, description, category_id, icon)\n`;
    sql += `VALUES (\n`;
    sql += `  ${sqlEscape(comp.name)},\n`;
    sql += `  ${sqlEscape(comp.slug)},\n`;
    sql += `  ${sqlEscape(comp.description)},\n`;
    sql += `  (SELECT id FROM public.categories WHERE slug = ${sqlEscape(comp.category_slug)}),\n`;
    sql += `  ${sqlEscape(comp.icon)}\n`;
    sql += `);\n\n`;
  }

  sql += `
-- ============================================================
-- COMPETENCY SYNONYMS
-- ============================================================

`;

  // PHASE 2: Add all synonyms
  for (const comp of sorted) {
    if (comp.synonyms && comp.synonyms.length > 0) {
      sql += `-- ${comp.name} synonyms\n`;
      for (const synonym of comp.synonyms) {
        sql += `INSERT INTO public.competency_synonyms (competency_id, synonym)\n`;
        sql += `VALUES ((SELECT id FROM public.competencies WHERE slug = ${sqlEscape(comp.slug)}), ${sqlEscape(synonym)});\n`;
      }
      sql += '\n';
    }
  }

  sql += `
-- ============================================================
-- COMPETENCY PREREQUISITES
-- ============================================================

`;

  // PHASE 3: Add all prerequisites (now all competencies exist)
  for (const comp of sorted) {
    if (comp.prerequisites && comp.prerequisites.length > 0) {
      sql += `-- ${comp.name} prerequisites\n`;
      for (const prereq of comp.prerequisites) {
        sql += `INSERT INTO public.competency_prerequisites (competency_id, prerequisite_id, prerequisite_level, notes)\n`;
        sql += `VALUES (\n`;
        sql += `  (SELECT id FROM public.competencies WHERE slug = ${sqlEscape(comp.slug)}),\n`;
        sql += `  (SELECT id FROM public.competencies WHERE slug = ${sqlEscape(prereq.prerequisite_slug)}),\n`;
        sql += `  ${sqlEscape(prereq.prerequisite_level)},\n`;
        sql += `  ${sqlEscape(prereq.notes)}\n`;
        sql += `);\n`;
      }
      sql += '\n';
    }
  }

  sql += `
-- ============================================================
-- COMPETENCY ALTERNATIVES
-- ============================================================

`;

  // PHASE 4: Add all alternatives
  for (const comp of sorted) {
    if (comp.alternatives && comp.alternatives.length > 0) {
      sql += `-- ${comp.name} alternatives\n`;
      for (const alt of comp.alternatives) {
        sql += `INSERT INTO public.competency_alternatives (competency_id, alternative_id, relationship_type, notes)\n`;
        sql += `VALUES (\n`;
        sql += `  (SELECT id FROM public.competencies WHERE slug = ${sqlEscape(comp.slug)}),\n`;
        sql += `  (SELECT id FROM public.competencies WHERE slug = ${sqlEscape(alt.alternative_slug)}),\n`;
        sql += `  ${sqlEscape(alt.relationship_type)},\n`;
        sql += `  ${sqlEscape(alt.notes)}\n`;
        sql += `);\n`;
      }
      sql += '\n';
    }
  }

  return sql;
}

function generateTopicsSQL(topics: Topic[]): string {
  let sql = `
-- ============================================================
-- TOPICS
-- ============================================================

`;

  // Sort by slug for consistency
  const sorted = [...topics].sort((a, b) => a.slug.localeCompare(b.slug));

  for (const topic of sorted) {
    sql += `-- ${topic.name}\n`;
    sql += `INSERT INTO public.topics (name, slug, description, category_id)\n`;
    sql += `VALUES (\n`;
    sql += `  ${sqlEscape(topic.name)},\n`;
    sql += `  ${sqlEscape(topic.slug)},\n`;
    sql += `  ${sqlEscape(topic.description)},\n`;
    sql += `  (SELECT id FROM public.categories WHERE slug = ${sqlEscape(topic.category_slug)})\n`;
    sql += `);\n\n`;

    // Add topic competencies
    if (topic.competencies && topic.competencies.length > 0) {
      for (const tc of topic.competencies) {
        sql += `INSERT INTO public.topic_competencies (topic_id, competency_id, is_primary)\n`;
        sql += `VALUES (\n`;
        sql += `  (SELECT id FROM public.topics WHERE slug = ${sqlEscape(topic.slug)}),\n`;
        sql += `  (SELECT id FROM public.competencies WHERE slug = ${sqlEscape(tc.competency_slug)}),\n`;
        sql += `  ${tc.is_primary}\n`;
        sql += `);\n`;
      }
      sql += '\n';
    }
  }

  return sql;
}

async function main() {
  console.log('🚀 Generating seed.sql from JSON files...\n');

  const seedsDir = path.join(process.cwd(), 'data/seeds');

  // Read all JSON files
  console.log('📖 Reading JSON files...');

  const categoriesData = JSON.parse(
    fs.readFileSync(path.join(seedsDir, 'categories.json'), 'utf-8')
  );

  const unsplashData = JSON.parse(
    fs.readFileSync(path.join(seedsDir, 'unsplash_images.json'), 'utf-8')
  );

  // Read all competency files
  const competenciesDir = path.join(seedsDir, 'competencies');
  const competencyFiles = fs.readdirSync(competenciesDir).filter(f => f.endsWith('.json'));
  const allCompetencies: Competency[] = [];

  for (const file of competencyFiles) {
    const data = JSON.parse(fs.readFileSync(path.join(competenciesDir, file), 'utf-8'));
    allCompetencies.push(...data.competencies);
    console.log(`  ✓ Read ${data.competencies.length} competencies from ${file}`);
  }

  // Read all topic files
  const topicsDir = path.join(seedsDir, 'topics');
  const topicFiles = fs.readdirSync(topicsDir).filter(f => f.endsWith('.json'));
  const allTopics: Topic[] = [];

  for (const file of topicFiles) {
    const data = JSON.parse(fs.readFileSync(path.join(topicsDir, file), 'utf-8'));
    allTopics.push(...data.topics);
    console.log(`  ✓ Read ${data.topics.length} topics from ${file}`);
  }

  console.log(`\n📊 Summary:`);
  console.log(`  • ${categoriesData.categories.length} categories`);
  console.log(`  • ${allCompetencies.length} competencies`);
  console.log(`  • ${allTopics.length} topics`);
  console.log(`  • ${unsplashData.images.length} unsplash images`);

  // Generate SQL
  console.log('\n🔨 Generating SQL...');
  let sql = generateHeader();
  sql += generateUnsplashImagesSQL(unsplashData.images);
  sql += generateCategoriesSQL(categoriesData.categories);
  sql += generateCompetenciesSQL(allCompetencies);
  sql += generateTopicsSQL(allTopics);

  // Write to file
  const outputPath = path.join(process.cwd(), 'supabase/seed.sql');
  fs.writeFileSync(outputPath, sql);

  console.log(`\n✅ Generated supabase/seed.sql`);
  console.log(`   ${sql.split('\n').length} lines`);

  console.log('\n✨ Generation complete!');
  console.log('\nNext steps:');
  console.log('1. Review: supabase/seed.sql');
  console.log('2. Run: supabase db reset');
  console.log('3. Test the application');
}

main().catch(console.error);
